[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking = "9aZRVnxzy8kRiq8mHcfFBj1BX2hY7ixUJH24Q4aYjycd"

[programs.testnet]
staking = "DVDvrhK9vFQ8JtXpv3pSskSQahuuQKPuWpJakHT4EJne"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/testnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
