[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking = "9aZRVnxzy8kRiq8mHcfFBj1BX2hY7ixUJH24Q4aYjycd"

[programs.testnet]
staking = "5HWYY9fuyvCrvV66GCg5hPbf7XARCcybuQrdJGGEbEVH"

[programs.devnet]
staking = "5HWYY9fuyvCrvV66GCg5hPbf7XARCcybuQrdJGGEbEVH"

[programs.mainnet]
staking = "4D9WKeKXKCEjzZfuLgU3H7P9J1cJ1HZ2fPURAX8ceqKc"

[registry]
url = "https://api.apr.dev"

[metadata]
name = "FIGHT Staking"
description = "Stake FIGHT tokens with owner-controlled pause functionality"
version = "0.1.0"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/testnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
